### ISSUE TITLE
Bug with markup rendering in version 0.2.9

### ISSUE THREAD

**Issue by helenb** [torchbox/django-pattern-library#119]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Upgrading the pattern library from 0.2.8 to 0.2.9 caused markup rendering inside the pattern library to break. Viewing an identical page without the pattern library did not cause any issues.

### Steps to Reproduce

For Ben's benefit, this can be tested on the GOSH repo on Torchbox's gitlab.

1. Set up a local build using the `main` branch
2. Update the configuration so the pattern library is at version 0.2.9
2. View the home page in the pattern library and compare the markup to the home page viewed without the pattern library
3. Downgrade to 0.2.8 and compare.

**Comment by bcdickinson** [comment]
This appears to be related to broken detection of "page" templates that don't need wrapping in the base template: https://github.com/torchbox/django-pattern-library/commit/a8f79ed7c9ac10a5406ac60b47a6d3b574b70a22#diff-8137058159488acb9fbce2f9ec4f9c9bL79
