### ISSUE TITLE
Need information on mocking context processors

### ISSUE THREAD

**Issue by thibaudcolas** [torchbox/django-pattern-library#134]
It’s unclear whether mocking context processors is supported, and if so how.

If it’s not supported, we need to document this at the very least.

Detailed feedback from @ababic:

> **Context processors are potentially misused/overused to get around limitations**

> For example, I've seen forms, various bits of text and other variables added via context processors to make things available when rendering via the pattern library. This is fine to a degree, but there could be better options (like using wagtail sitesettings) that are overlooked because they are more difficult to integrate with the pattern library

### Which terms did you search for in the docs and issues?

- [x] In the documentation I searched for: context processors
- [x] In the issues / pull requests, I searched for: context processors

**Comment by ababic** [comment]
Hey @thibaudcolas. This is more a symptom, rather than a problem in itself. The issue is that adding a context processor is sometimes the only option to inject complex objects into the template context. I think there have been some improvements  in this area since I raised this.

**Comment by thibaudcolas** [comment]
Thank you @ababic, re-reading this I did completely misunderstand this.
