### ISSUE TITLE
Cannot get started with django-pattern-library

### ISSUE THREAD

**Issue by jenish2014** [torchbox/django-pattern-library#143]
I followed the getting started section from the docs but got stuck, it keeps showing me PatternLibraryEmpty error.

my directory structure:

```
project
    - home
         - templates
             - patterns
                  - base.html
                 - components
                     - quote_block
    - project_dir
    - manage.py
```

i've setup the settings file as instructed on getting started page but cannot get it to work. help!

**Comment by thibaudcolas** [comment]
Hey @jenish2014, could you share more info about your setup? I think we’d need your template and pattern library settings at least.
