### ISSUE TITLE
Pattern library does not load CSS or JavaScript in IE11

### ISSUE THREAD

**Issue by helenb** [torchbox/django-pattern-library#151]
### Issue Summary

If you view the pattern library in IE11 (tested with browserstack) it does not load the CSS and JS. The console is reporting a syntax error

### Steps to Reproduce

1. Open a new session of IE11 in Browserstack
2. Visit a pattern library page

![Screenshot 2021-07-23 at 13 35 12](https://user-images.githubusercontent.com/771869/126787737-6696a085-4b82-485c-ac38-deca1695f1bd.png)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

Tested on wagtail-kit which is using pattern library version 0.3.0
Tested on action for children which is using pattern library version 0.5.0

The console reports a syntax error but it is hard to see what this is in the compiled and compressed code:
![Screenshot 2021-07-23 at 14 18 09](https://user-images.githubusercontent.com/771869/126787644-1a714bc4-f64d-4576-9c3f-1710f3f7eea1.png)
![Screenshot 2021-07-23 at 14 17 59](https://user-images.githubusercontent.com/771869/126787653-5c75218b-793d-49dd-b4c1-9c0289b25333.png)

**Comment by zerolab** [comment]
I think it is high time we stopped supporting IE11, no?

**Comment by thibaudcolas** [comment]
PR to fully remove support: https://github.com/torchbox/django-pattern-library/pull/162

We still have a lot of projects with IE11 support targets, so I think it’s important individual patterns can still be rendered correctly in IE11, but the pattern library UI doesn’t have to support it.
