### ISSUE TITLE
When I run pytest i get a warning about default_app_config

### ISSUE THREAD

**Issue by simkimsia** [torchbox/django-pattern-library#153]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When i run pytest, i get a warning 

```
RemovedInDjango41Warning: 'pattern_library' defines default_app_config = 'pattern_library.apps.PatternLibraryAppConfig'. Django now detects this configuration automatically. You can remove default_app_config.
    app_config = AppConfig.create(entry)
```

### Steps to Reproduce

Install pattern-library.
Run pytest

### Technical details

This is due to django 3.2 

also see this PR for allauth that has a similar issue. https://github.com/pennersr/django-allauth/pull/2829

**Comment by thibaudcolas** [comment]
Fixed in #160.
