### ISSUE TITLE
'pattern_library' defines default_app_config

### ISSUE THREAD

**Issue by nickmoreton** [torchbox/django-pattern-library#159]
### Is your proposal related to a problem?

When used with Django 3.2, django-pattern-library is throwing deprecation warnings about the use of the defafult_app_config:

```
/usr/local/lib/python3.8/site-packages/django/apps/registry.py:91: RemovedInDjango41Warning: 'pattern_library' defines default_app_config = 'pattern_library.apps.PatternLibraryAppConfig'. Django now detects this configuration automatically. You can remove default_app_config.
```

### Describe the solution you'd like

remove: `default_app_config = 'pattern_library.apps.PatternLibraryAppConfig'` when using Django >= 3.2

### Describe alternatives you've considered

I will create a PR for this.

### Additional context

https://docs.djangoproject.com/en/3.2/ref/applications/#for-application-authors

**Comment by thibaudcolas** [comment]
Hey @nickmoreton, this has already been reported in #153 so I’ll close this issue. PR definitely welcome!
