### ISSUE TITLE
Allow `.yml` as YAML file extension

### ISSUE THREAD

**Issue by tbrlpld** [torchbox/django-pattern-library#161]
### Issue Summary

When defining template context files (the YAML) files, these are only recognised when they use the full `.yaml` extension. 

When using the shorter `.yml` extension the template is not picking up the context file. 

This can be very confusing. 

### Steps to Reproduce

1. Setup a project with `django-patter-library` enable
2. Create a template `test.html` in one of the directories observed by `django-pattern-library` with the content 

 ```django
{{ test_var }}
````

3. Create a context file `test.yaml` next to the template with the content

```yaml
context:
  test_var: Test content
````

4. Open the template in the patter library and observe that you see "Test content"
5. Rename the context file `mv test.yaml test.yml`
6. Open the template in the patter library and observe that you see nothing. The context is not rendered anymore.

**Comment by thibaudcolas** [comment]
👍 I like the idea.

It seems this would be pretty simple to do here: https://github.com/torchbox/django-pattern-library/blob/main/pattern_library/utils.py#L148

PR welcome!
