### ISSUE TITLE
Django 4.0 compatibility issue: Node.render should return a string

### ISSUE THREAD

**Issue by thibaudcolas** [torchbox/django-pattern-library#166]
### Issue Summary

cc @nickmoreton who fixed our test data in #165. Our test suite was failing in Django 4.0 because the new version of Django assumes the output of `Node.render` is a string. The error we got in our test suites was from Django’s templates rendering:

```
sequence item 4: expected str instance, NoneType found
```

This was a misc. performance improvement – from the [release notes](https://docs.djangoproject.com/en/4.0/releases/4.0/#miscellaneous):

> NodeList.render() no longer casts the output of render() method for individual nodes to a string. Node.render() should always return a string as documented.

Corresponding PR: https://github.com/django/django/pull/14503, and [blame of those three lines](https://github.com/django/django/blame/19fb838803f63eef0726a370050443b693f109be/django/template/base.py#L977-L979).

### Steps to Reproduce

Use this library and override a tag by providing [raw data](https://torchbox.github.io/django-pattern-library/guides/overriding-template-tags/#return-raw-data), with a value other than a string as the tag output.

### Potential fixes

One option would be for us to re-introduce this casting for backwards compatibility. I believe it’s only needed here: https://github.com/torchbox/django-pattern-library/blob/dffd369bd254401279136ffa9f299bc8d1fa8c5e/pattern_library/monkey_utils.py#L78

Another option would be to keep our implementation as-is and document the issue so people upgrading to Django 4.0 are aware they’ll need to change their `raw` definitions to be strings. We’d also want to remove/change the test cases updated in #165, as right now they aren’t testing much. We could also consider adding an `assert` for this in our code / check the type and throw a custom exception. Not too sure if worthwhile or not.

**Comment by thibaudcolas** [comment]
@zerolab @bcdickinson when you have a chance I could use your input on this. Would be great for us to agree on a fix before lots of our projects start upgrading to Django 4.0.

**Comment by zerolab** [comment]
My gut feeling is that we should handle this ourselves since we're kind of acting (in a veeery loose sense of the concept) like a fancy `NodeList` with individual bits patched.

Also, will save updating hundreds of yaml files
