### ISSUE TITLE
Template tags can't be overwritten under Django v4.1

### ISSUE THREAD

**Issue by vorlif** [torchbox/django-pattern-library#203]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Template tags cannot be overwritten under Django v4.1 because a [check has been introduced](https://github.com/django/django/pull/15005) to prevent this.

```text
ERRORS:
?: (templates.E003) 'wagtailcore_tags' is used for multiple template tag modules: 'project.project_styleguide.templatetags.wagtailcore_tags', 'wagtail.templatetags.wagtailcore_tags'
?: (templates.E003) 'wagtailimages_tags' is used for multiple template tag modules: 'project.project_styleguide.templatetags.wagtailimages_tags', 'wagtail.images.templatetags.wagtailimages_tags'
```

### Workaround:

Disable the check in the settings:

```diff
+ SILENCED_SYSTEM_CHECKS = ["templates.E003"]
```

### Steps to Reproduce

1. Follow the documentation to overwrite a tag
2. Start the server `python manage.py runserver`

Please tell me if more detailed instructions are needed.

### Technical details

- Python version: v3.10.7
- Django version: 4.1.2
- Browser version: Not relevant

**Comment by thibaudcolas** [comment]
Thank you for the report @vorlif! I’m surprised we’ve not run into this yet, it could be because we don’t make use of system checks, or we’re still slow to upgrade to Django v4.1.
