### ISSUE TITLE
ci: tox.ini is outdated and other related issues 

### ISSUE THREAD

**Issue by simkimsia** [torchbox/django-pattern-library#218]
Related issues:

1. tox no longer supports whitelist_externals See https://github.com/python-poetry/poetry/pull/7341 for details
2. tox cannot detect tool.poetry.dev-dependencies, so the solution adopted is to use tool.poetry.extras instead. Drawback is whenever use `poetry install` in the normal poetry virtual environment an extra call to poetry install --extras 'test' is required. See https://github.com/orgs/python-poetry/discussions/4307#discussioncomment-1041658 for details
3. Recommend that tox_install.sh to be deleted, but this is not necessary for now.

This is related to #214, #215, #216. 

Detected when trying to solve #212 and #213

**Comment by zerolab** [comment]
Fixed in #220
