### ISSUE TITLE
Support Django 5.0

### ISSUE THREAD

**Issue by llPekoll** [torchbox/django-pattern-library#235]
Hello,
This is what we get when we try to install django-pattern-library with just released django 5.0
```
Because no versions of django-pattern-library match >1.1.0,<2.0.0
 and django-pattern-library (1.1.0) depends on Django (>=3.2,<5.0), django-pattern-library (>=1.1.0,<2.0.0) requires Django (>=3.2,<5.0).
So, because recettes depends on both django (^5.0) and django-pattern-library (^1.1.0), version solving failed.
```
Django 5.0 doesn't seem to change templates a lot. Maybe you just need to upgrade versions.

Best Regards

Yohann

**Comment by zerolab** [comment]
@llPekoll feel free to submit a PR

Things that need updating:
* https://github.com/torchbox/django-pattern-library/blob/main/pyproject.toml#L46, change to <5.1
* https://github.com/torchbox/django-pattern-library/blob/main/pyproject.toml#L27, add `"Framework :: Django :: 5.0",
* https://github.com/torchbox/django-pattern-library/blob/main/tox.ini - add Django 5.0 to the matrix. Bonus points, add Python 3.12 for 5.0 and main
* https://github.com/torchbox/django-pattern-library/blob/main/.github/workflows/ci.yml#L23-L40, add Django 5.0 to the mix

**Comment by llPekoll** [comment]
Just made the PR, tell me if i need to change stuff!
Best
