### ISSUE TITLE
Document pattern name overrides

### ISSUE THREAD

**Issue by thibaudcolas** [torchbox/django-pattern-library#98]
From @chris-lawton in #11.

**Comment by bcdickinson** [comment]
This is already possible by specifying a `name: ...` key at the top level of the YAML file for a pattern: https://github.com/torchbox/django-pattern-library/blob/930da7df7b68400720a26bf6c1b429324fb93a61/tests/templates/patterns/molecules/test_molecule/test_molecule.yaml#L1

I'll change this issue to be for adding documentation for that.
